<a href="https://colab.research.google.com/github/ZinMinThaw-23/Explicit-Content-Detection/blob/main/Explict%20and%20Nonexplicit%20Data%20Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

Data Understanding

In [ ]:
train_data=pd.read_csv("/content/sample_data/california_housing_train.csv")

In [ ]:
train_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [ ]:
train_data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

Data Preprocessing

In [ ]:
for i in train_data.columns:
  print(i)
  print(train_data[i].isnull().unique())
  print()

longitude
[False]

latitude
[False]

housing_median_age
[False]

total_rooms
[False]

total_bedrooms
[False]

population
[False]

households
[False]

median_income
[False]

median_house_value
[False]



In [ ]:
X_train=train_data.iloc[:,:-1].values
print(X_train)

[[-114.31     34.19     15.     ... 1015.      472.        1.4936]
 [-114.47     34.4      19.     ... 1129.      463.        1.82  ]
 [-114.56     33.69     17.     ...  333.      117.        1.6509]
 ...
 [-124.3      41.84     17.     ... 1244.      456.        3.0313]
 [-124.3      41.8      19.     ... 1298.      478.        1.9797]
 [-124.35     40.54     52.     ...  806.      270.        3.0147]]


In [ ]:
Y_train=train_data.iloc[:,-1]
print(Y_train)

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64


Data Modeling

In [ ]:
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
model1=LinearRegression()
model2=DecisionTreeClassifier()

In [ ]:
model1.fit(X_train,Y_train)

LinearRegression()

In [ ]:
model2.fit(X_train,Y_train)

DecisionTreeClassifier()

Data Evaluation

In [ ]:
test_data=pd.read_csv("/content/sample_data/california_housing_test.csv")

In [ ]:
test_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [ ]:
test_data.describe()

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000   273.00000       2.544000   
50%        437.000000   1155.000000   409.50000       3.487150   
75%        636.000000   1742.750000   597.25000       4.656475   
max       5419.000000  11935.000000  4930.00000      15.000100   

       median_house_value  
count          3000.00000  
mean         205846.27500  
std          113119.68747  
min           22500.00000  
25%          121200.00000  
50%          177650.00000  
75%          263975.00000  
max          500001.00000

In [ ]:
for i in test_data.columns:
  print(i)
  print(test_data[i].isnull().unique())
  print()

In [ ]:
X_test=test_data.iloc[:,:-1]
Y_test=test_data.iloc[:,-1]

In [ ]:
Y_pred1=model1.predict(X_test)
Y_pred2=model2.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [ ]:
def meansquareerror(Y_pred,Y_test):
  for i in range(len(Y_pred)):
    total=0
    SE=(Y_pred-Y_test)**2
    total+=SE
  MSE=total/len(Y_pred)
  print("Mean Square Error for this regression is",MSE)
  return MSE

In [ ]:
LG_MSE=meansquareerror(Y_pred1,Y_test)

Mean Square Error for this regression is 0       2.193653e+04
1       4.372406e+05
2       1.134305e+03
3       8.274716e+04
4       4.799213e+05
            ...     
2995    4.229078e+05
2996    1.166412e+06
2997    2.291731e+05
2998    8.667537e+04
2999    6.226962e+05
Name: median_house_value, Length: 3000, dtype: float64


In [ ]:
DT_MSE=meansquareerror(Y_pred2,Y_test)

Mean Square Error for this regression is 0       1.442133e+05
1       4.033333e+06
2       3.619213e+06
3       2.285280e+06
4       2.296333e+04
            ...     
2995    3.333333e+06
2996    3.598403e+06
2997    1.763333e+03
2998    2.842133e+05
2999    0.000000e+00
Name: median_house_value, Length: 3000, dtype: float64


In [ ]:
MSE_difference=LG_MSE-DT_MSE
print("Mean Square Error Difference is",MSE_difference)

Mean Square Error Difference is 0      -1.222768e+05
1      -3.596093e+06
2      -3.618079e+06
3      -2.202533e+06
4       4.569580e+05
            ...     
2995   -2.910426e+06
2996   -2.431992e+06
2997    2.274097e+05
2998   -1.975380e+05
2999    6.226962e+05
Name: median_house_value, Length: 3000, dtype: float64
